###
### Add a new post
POST http://localhost:3000/post
Content-Type: application/json

{
	"title": "First post",
	"body": "This is a test post",
	"senderId": "user1"
}

###
### Get all posts
GET http://localhost:3000/post

###
### Get posts by sender
GET http://localhost:3000/post?sender=user1

###
### Get a post by id
GET http://localhost:3000/post/{{postId}}

###
### Update a post (replace)
PUT http://localhost:3000/post/{{postId}}
Content-Type: application/json

{
	"title": "Updated title",
	"body": "Updated body",
	"senderId": "user1"
}

###
GET http://localhost:3000/
###
GET http://localhost:3000/REST
